# Generated by Django 4.1.2 on 2022-11-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_image_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../media/profile_default.webp', upload_to='images/'),
        ),
    ]
