# Generated by Django 4.1.2 on 2022-11-24 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Please provide a project title', max_length=254)),
                ('project_description', models.CharField(default='Please provide a project description', max_length=500)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_live_link', models.URLField(blank=True, max_length=265, null=True)),
                ('project_github_link', models.URLField(blank=True, max_length=265, null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('html', models.BooleanField(default=False)),
                ('css', models.BooleanField(default=False)),
                ('bootstrap', models.BooleanField(default=False)),
                ('javascript', models.BooleanField(default=False)),
                ('python', models.BooleanField(default=False)),
                ('flask', models.BooleanField(default=False)),
                ('django', models.BooleanField(default=False)),
                ('sql', models.BooleanField(default=False)),
                ('mongodb', models.BooleanField(default=False)),
                ('postgres', models.BooleanField(default=False)),
                ('deployment_required', models.BooleanField(default=False)),
                ('shared_hosting', models.BooleanField(default=False)),
                ('vps', models.BooleanField(default=False)),
                ('email_server_setup', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
