# Generated by Django 4.1.3 on 2023-04-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(default='../media/img-commig-soon.webp', upload_to='images/'),
        ),
    ]
