# Generated by Django 4.1.3 on 2023-04-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='aws',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='heroku',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='materialize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='reactJS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='use_database',
            field=models.BooleanField(default=False),
        ),
    ]
