# Generated by Django 4.1.3 on 2023-04-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_aws_projects_heroku_projects_is_deployed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='stripe',
            field=models.BooleanField(default=False),
        ),
    ]
